[package]
name = "dinoscript_std"
version = "0.1.0"
edition = "2021"
default-run = "build_std"

[dependencies]
dinoscript_core = { path = "../dinoscript_core" }

[features]
build_ds = []

[build-dependencies]
dinoscript_core = { path = "../dinoscript_core" }